# Generated by Django 6.0.7 on 2026-08-28 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_business_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='allow_cashier_custom_price',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='business',
            name='allow_cashier_debts',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='business',
            name='show_buying_price_to_cashier',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='business',
            name='show_profit_to_cashier',
            field=models.BooleanField(default=False),
        ),
    ]
