# Generated by Django 6.0.7 on 2026-08-28 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_business_allow_cashier_custom_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='settings_password',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
