# Generated by Django 6.0.7 on 2026-08-28 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_business_settings_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='show_stock_summary_cards',
            field=models.BooleanField(default=False),
        ),
    ]
