# Generated by Django 6.0.7 on 2026-09-29 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_business_show_stock_summary_cards'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionpayment',
            name='plan',
            field=models.CharField(choices=[('MONTHLY', 'Monthly Plan'), ('ANNUAL', 'Annual Plan')], default='MONTHLY', max_length=20),
        ),
    ]
