# Generated by Django 6.0.7 on 2026-07-29 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_business_address'),
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['business', 'barcode'], name='inventory_p_busines_23b9b6_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['business', 'name'], name='inventory_p_busines_c181c4_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['business', 'is_active'], name='inventory_p_busines_dc2763_idx'),
        ),
    ]
