# Generated by Django 6.0.7 on 2026-08-24 10:23

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_business_is_active_subscription_and_more'),
        ('sales', '0003_customer_debt_debtpaymenthistory'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(help_text='Mfano: LUKU ya dukani, Chakula cha mchana', max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('category', models.CharField(choices=[('UTILITIES', 'Umeme / Maji'), ('FOOD', 'Chakula / Vinywaji'), ('TRANSPORT', 'Usafiri / Nauli'), ('SUPPLIES', 'Vifaa vya Ofisi'), ('OTHER', 'Mengineyo')], default='OTHER', max_length=50)),
                ('description', models.TextField(blank=True, help_text='Maelezo fupi ya ziada', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='accounts.business')),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses_recorded', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
